In [2]:
import pandas as pd
import numpy as np
import csv

In [3]:
artworks_db = pd.read_json('artworks.json')
artworks_db.set_index('id', drop=True,inplace=True)
artworks_db.head()

,game,height,image_id,url,width,checksum,artwork_type,alpha_channel,animated
id,,,,,,,,,
2,23248,1080.0,nfoayruxc3ze4yccf5ey,//images.igdb.com/igdb/image/upload/t_thumb/nf...,1920.0,a9cc2277-18f4-5ce6-0cf3-54f7a9c46c77,1.0,NaN,NaN
3,23248,1080.0,bzmmhgsskzw2plzpmabo,//images.igdb.com/igdb/image/upload/t_thumb/bz...,1920.0,358ce8a7-0f23-f03b-e9f1-61d2481ee1ac,1.0,NaN,NaN
4,23248,1080.0,qira2bnppcegot3dzlgk,//images.igdb.com/igdb/image/upload/t_thumb/qi...,1920.0,48e6cf03-f489-859a-f63d-45bd5962c253,1.0,NaN,NaN
7,31712,1160.0,p9yyozft35nx7aoi8khj,//images.igdb.com/igdb/image/upload/t_thumb/p9...,1920.0,8d348787-128b-3d04-74b3-7761f20047a2,1.0,NaN,NaN
8,16999,3530.0,kxwrcnqgh1nffr9vg4ly,//images.igdb.com/igdb/image/upload/t_thumb/kx...,6160.0,e4889922-b704-0187-d46f-3ad9fd0c19e6,1.0,NaN,NaN

In [4]:
companies_db = pd.read_json('companies.json')
companies_db.set_index('id', drop=True,inplace=True)
companies_db.head()

,change_date_category,country,created_at,description,developed,logo,name,parent,published,slug,start_date,updated_at,url,websites,checksum,status,start_date_format,change_date,changed_company_id
id,,,,,,,,,,,,,,,,,,,
444,7,124.0,2011-10-04 10:38:08,Radical Entertainment Inc. is a Canadian video...,"[3869, 3949, 3954, 2844, 5139, 5868, 210116, 8...",387.0,Radical Entertainment,66.0,[42246],radical-entertainment,683683200.0,2025-10-30 12:56:18,https://www.igdb.com/companies/radical-enterta...,[506],9b059e2c-2d98-ee7f-edd8-2253a0ffafec,0,1,NaN,NaN
221,7,826.0,2011-04-08 12:59:45,Splash Damage Ltd. is an independent British v...,"[502, 2987, 680, 28991, 28990, 103291, 1902, 2...",304.0,Splash Damage,NaN,[228536],splash-damage,988675200.0,2025-11-27 16:07:22,https://www.igdb.com/companies/splash-damage,[75],71e703ca-8f1e-b26f-3abc-1877a4302a15,0,1,NaN,NaN
19,7,250.0,2011-03-04 18:57:50,"Founded in 1999, Arkane Studios has grown to b...","[533, 11118, 51690, 19531, 52899, 103306, 1033...",7885.0,Arkane Studios,245.0,[602],arkane-studios,938736000.0,2025-11-12 12:24:53,https://www.igdb.com/companies/arkane-studios,[326],b19b527c-90a2-b917-b887-1c995619cb6d,0,0,NaN,NaN
302,0,NaN,2011-04-13 09:20:57,NaN,"[40, 47385]",NaN,Massive Bear Studios,NaN,NaN,massive-bear-studios,NaN,2025-09-06 15:32:41,https://www.igdb.com/companies/massive-bear-st...,NaN,12c9a826-df2e-a32b-183c-fa62e4f604cd,0,0,NaN,NaN
165,0,NaN,2011-03-30 19:43:08,NaN,NaN,NaN,DC Entertainment,NaN,"[501, 138185, 25993, 26113, 26114, 26111, 2599...",dc-entertainment,NaN,2025-09-06 15:31:00,https://www.igdb.com/companies/dc-entertainment,NaN,70f70a16-fd9b-ebf6-45a4-147cb91616ce,0,0,NaN,NaN

In [5]:
# with open('covers.json', 'r') as f:
#     content = f.read().strip()
#     print(f"File content length: {len(content)}")
#     print(f"First 50 characters: {content[:500]}")
covers_db = pd.read_json('covers.json')
covers_db.set_index('id', drop=True,inplace=True)
covers_db.head()

,game,height,image_id,url,width,checksum,alpha_channel,animated,game_localization
id,,,,,,,,,
109,108.0,500.0,pmjszoa4lgd7nznewajq,//images.igdb.com/igdb/image/upload/t_thumb/pm...,384.0,e057cbf1-a627-8cb4-6fc5-021a5e06403d,NaN,NaN,NaN
243,252.0,670.0,vqf2wnwpoktu231nfc2p,//images.igdb.com/igdb/image/upload/t_thumb/vq...,553.0,6d0c6b77-19c3-0f5f-563a-bb1bae8a6203,NaN,NaN,NaN
249,258.0,650.0,eojokuktlkawq6nr1v9i,//images.igdb.com/igdb/image/upload/t_thumb/eo...,665.0,f29574c5-ede1-4c68-1e40-e2b5887191fc,NaN,NaN,NaN
250,259.0,351.0,eye80lpmtwdjqjzww7jz,//images.igdb.com/igdb/image/upload/t_thumb/ey...,350.0,8f1440ff-ca33-6c9b-a168-78299f7ea4d2,NaN,NaN,NaN
252,261.0,300.0,gzwehl7lyeabjbglisl4,//images.igdb.com/igdb/image/upload/t_thumb/gz...,214.0,dc82d74f-1976-25e8-925b-bc26bbafbebb,NaN,NaN,NaN

In [6]:
games_db = pd.read_json('games.json')
games_db.set_index('id', drop=True,inplace=True)
games_db.drop('created_at', axis=1, inplace=True)
games_db.drop('updated_at', axis=1, inplace=True)
games_db.head()

,age_ratings,aggregated_rating,aggregated_rating_count,alternative_names,bundles,cover,expansions,external_games,first_release_date,franchise,...,parent_game,remasters,ports,dlcs,standalone_expansions,forks,hypes,remakes,version_parent,version_title
id,,,,,,,,,,,,,,,,,,,,,
145,"[15740, 32527]",75.00,3.0,"[17153, 27771, 42498]","[150523, 77212]",128838.0,"[147, 146, 206]","[148425, 245995]",1.056586e+09,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,"[45966, 371, 69596]",90.00,1.0,[82107],NaN,89377.0,NaN,"[32645, 217574, 149077, 2594701, 246112]",1.045181e+09,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,"[63718, 33972, 63719, 33973]",80.25,4.0,"[35085, 35088, 55074, 57346, 57347]",NaN,134738.0,NaN,"[143914, 51753, 403402, 247800]",1.194307e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
462,"[86688, 123695]",20.00,1.0,"[18656, 40756]",NaN,274020.0,NaN,"[155975, 1918838, 41318, 2520260]",1.172189e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,"[5599, 124411]",NaN,NaN,"[152614, 152615, 152971, 177479, 180664]",NaN,93277.0,NaN,"[1919075, 137790, 2069292]",8.794656e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
genres_db = pd.read_json('genres.json')
genres_db.set_index('id', drop=True,inplace=True)
genres_db.head()
genres_db.drop('created_at', axis=1, inplace=True)
genres_db.drop('updated_at', axis=1, inplace=True)
genres_db.head()

,name,slug,url,checksum
id,,,,
2,Point-and-click,point-and-click,https://www.igdb.com/genres/point-and-click,b295f28a-5f68-fc3e-5de2-f3195e10d160
4,Fighting,fighting,https://www.igdb.com/genres/fighting,d23da988-5bb7-011e-34dc-0b712765e470
5,Shooter,shooter,https://www.igdb.com/genres/shooter,20c255bc-ec2d-c219-34bd-47995b0a79f1
7,Music,music,https://www.igdb.com/genres/music,cbf12469-a5a8-6974-086c-ec9c6aeb5791
8,Platform,platform,https://www.igdb.com/genres/platform,06c188b9-1058-933f-dfee-4ec658117ad2

In [8]:
involved_companies_db = pd.read_json('involved_companies.json')
involved_companies_db.set_index('id', drop=True,inplace=True)
involved_companies_db.head()

KeyboardInterrupt:

In [9]:
platforms_db = pd.read_json('platforms.json')
platforms_db.set_index('id', drop=True,inplace=True)
platforms_db.drop('created_at', axis=1, inplace=True)
platforms_db.drop('updated_at', axis=1, inplace=True)
platforms_db.head()

,alternative_name,generation,name,platform_logo,slug,url,versions,websites,checksum,platform_type,abbreviation,platform_family,summary
id,,,,,,,,,,,,,
376,YENO Super Cassette Vision,3.0,Epoch Super Cassette Vision,743.0,epoch-super-cassette-vision,https://www.igdb.com/platforms/epoch-super-cas...,[494],[273],c02e43ee-1200-a498-3eb1-ed0cc6691245,1.0,NaN,NaN,NaN
12,X360,7.0,Xbox 360,622.0,xbox360,https://www.igdb.com/platforms/xbox360,"[2, 3, 495, 83]",[4],438d1189-ff91-b903-3c3a-a78c43d4435a,1.0,X360,2.0,Xbox 360 brings you a total games and entertai...
32,"JVC Saturn, Hi-Saturn, Samsung Saturn, V-Saturn",5.0,Sega Saturn,49.0,saturn,https://www.igdb.com/platforms/saturn,[65],[6],cdaf13fa-2d36-a314-5a4e-e729e9b7d408,1.0,Saturn,3.0,NaN
62,NaN,5.0,Atari Jaguar,286.0,jaguar,https://www.igdb.com/platforms/jaguar,[28],NaN,0dc2c454-5045-3c8d-8a9d-410cbb27afd8,1.0,Jaguar,NaN,NaN
148,NaN,NaN,AY-3-8607,NaN,ay-3-8607,https://www.igdb.com/platforms/ay-3-8607,[211],NaN,87f49579-c52e-8274-5aa1-0bfc227b3281,1.0,NaN,NaN,NaN

In [12]:
franchises_db = pd.read_json('franchises.json')
franchises_db.set_index('id', drop=True,inplace=True)
franchises_db.drop('created_at', axis=1, inplace=True)
franchises_db.drop('updated_at', axis=1, inplace=True)
franchises_db.head()

,games,name,slug,url,checksum
id,,,,,
295,[4815],The Dog,the-dog,https://www.igdb.com/franchises/the-dog,01cc866b-0d90-4a83-4335-78a47ac495f2
144,"[2785, 2809, 2810, 3248, 21151, 241137, 259229...",Johnny Bravo,johnny-bravo,https://www.igdb.com/franchises/johnny-bravo,b0e12f7d-9893-b13e-cb1d-9f296f1e3610
21,[140690],BloodRayne,bloodrayne,https://www.igdb.com/franchises/bloodrayne,aebed9e5-3623-548b-b663-5418391cd69a
215,"[4003, 5005, 12898, 119167, 43745, 69996, 1990...",Men in Black,men-in-black,https://www.igdb.com/franchises/men-in-black,12e09d89-e4e0-cf09-8729-49d4409d379e
163,"[3763, 300925, 354104, 95099, 63420, 324566]",Pacific Rim,pacific-rim,https://www.igdb.com/franchises/pacific-rim,194eece4-7391-8e9e-82dc-4f1343d597bc

In [16]:
game_modes_db = pd.read_json('game_modes.json')
game_modes_db.set_index('id', drop=True,inplace=True)
game_modes_db.drop('created_at', axis=1, inplace=True)
game_modes_db.drop('updated_at', axis=1, inplace=True)
game_modes_db.head()

,name,slug,url,checksum
id,,,,
1,Single player,single-player,https://www.igdb.com/game_modes/single-player,1cc07088-c5fb-3cb2-9e68-af6620c18836
2,Multiplayer,multiplayer,https://www.igdb.com/game_modes/multiplayer,3ffef62b-e19f-6bab-d510-98385c06d902
3,Co-operative,co-operative,https://www.igdb.com/game_modes/co-operative,d154173b-5bdf-5fda-5969-e4c87e135d1a
4,Split screen,split-screen,https://www.igdb.com/game_modes/split-screen,a165517f-f166-79cb-1290-d8c8d4f157a8
5,Massively Multiplayer Online (MMO),massively-multiplayer-online-mmo,https://www.igdb.com/game_modes/massively-mult...,631ae92b-e28d-8089-dd44-48cd2febf4ea

In [19]:
release_dates_db = pd.read_json('release_dates.json')
release_dates_db.set_index('id', drop=True,inplace=True)
release_dates_db.drop('created_at', axis=1, inplace=True)
release_dates_db.drop('updated_at', axis=1, inplace=True)
release_dates_db.head()

,date,game,human,m,platform,y,checksum,date_format,release_region,status
id,,,,,,,,,,
139,1.319501e+09,343,"Oct 25, 2011",10.0,6,2011.0,5a56b1f6-3226-4912-307b-d5ef6edc825c,0,8,NaN
128,1.248912e+09,215,"Jul 30, 2009",7.0,14,2009.0,95dd9bd0-4cd6-c4ff-a828-881bdbd9f614,0,8,NaN
333,1.204589e+09,468,"Mar 04, 2008",3.0,6,2008.0,21e6ec6e-76df-1a00-5262-3cbf47f8a959,0,8,NaN
119,1.255392e+09,212,"Oct 13, 2009",10.0,12,2009.0,7e3f38b9-e9e5-8814-f938-8361f756f625,0,8,NaN
48,1.101168e+09,123,"Nov 23, 2004",11.0,14,2004.0,597c4e9b-f7b1-d7df-be5b-51855c2460b6,0,8,NaN

In [23]:
screenshots_db = pd.read_json('screenshots.json')
screenshots_db.set_index('id', drop=True,inplace=True)
screenshots_db.head()

,alpha_channel,animated,game,height,image_id,url,width,checksum
id,,,,,,,,
499000,0.0,0.0,153519,1080.0,scap14,//images.igdb.com/igdb/image/upload/t_thumb/sc...,1920.0,af8ae9ff-f473-613d-a957-ae9161265e5a
499001,0.0,0.0,153519,1080.0,scap15,//images.igdb.com/igdb/image/upload/t_thumb/sc...,1920.0,86aa5366-45c5-a18d-42d4-a324c343a177
499002,0.0,0.0,73152,480.0,scap16,//images.igdb.com/igdb/image/upload/t_thumb/sc...,704.0,ddfff066-1a58-620c-c9fe-daa9d3174fde
499003,0.0,0.0,73152,480.0,scap17,//images.igdb.com/igdb/image/upload/t_thumb/sc...,704.0,aa7dd544-cf04-1679-5c1c-5adc49f66622
499004,0.0,0.0,73152,323.0,scap18,//images.igdb.com/igdb/image/upload/t_thumb/sc...,474.0,e7808dd6-0400-d284-c7d3-ce32c57090a5

In [21]:
themes_db = pd.read_json('themes.json')
themes_db.set_index('id', drop=True,inplace=True)
themes_db.drop('created_at', axis=1, inplace=True)
themes_db.drop('updated_at', axis=1, inplace=True)
themes_db.head()

,name,slug,url,checksum
id,,,,
31,Drama,drama,https://www.igdb.com/themes/drama,a10308c4-a660-7016-742b-ec956e9e9675
32,Non-fiction,non-fiction,https://www.igdb.com/themes/non-fiction,64d7a553-bbf8-1bbb-fc3c-8b1f7e404f5e
33,Sandbox,sandbox,https://www.igdb.com/themes/sandbox,e2f2c5b2-16ea-6e44-e2bb-af500d0b3f97
34,Educational,educational,https://www.igdb.com/themes/educational,91f581b0-62df-6d68-b7fc-1d4f1bc6d4fa
35,Kids,kids,https://www.igdb.com/themes/kids,95416d52-fb76-9995-f035-ee86bafbe5c4

In [27]:
keywords_db = pd.read_json('keywords.json')
keywords_db.set_index('id', drop=True,inplace=True)
keywords_db.drop('created_at', axis=1, inplace=True)
keywords_db.drop('updated_at', axis=1, inplace=True)
keywords_db.head()

,name,slug,url,checksum
id,,,,
497,summoning support,summoning-support,https://www.igdb.com/categories/summoning-support,12253aae-f527-2afb-f9fd-e2f760513c24
44,ice hockey,ice-hockey,https://www.igdb.com/categories/ice-hockey,51dfbc03-e82a-db6c-af06-d642a5ca7bd1
51,space strategy,space-strategy,https://www.igdb.com/categories/space-strategy,a253f912-5e2e-8f80-70e3-b1548333b340
313,rugby,rugby,https://www.igdb.com/categories/rugby,1c310b60-20bd-62b9-5680-104a19b0e823
66,simulated reality,simulated-reality,https://www.igdb.com/categories/simulated-reality,197b1124-3dd2-500f-94d9-bd15e30f9a34

In [20]:

collections_db = pd.read_json('collections.json')
collections_db.head()
collections_db.set_index('id', drop=True,inplace=True)
collections_db.drop('created_at', axis=1, inplace=True)
collections_db.drop('updated_at', axis=1, inplace=True)
# collections_db.head(10)

,games,name,slug,url,checksum,type,as_child_relations,as_parent_relations
id,,,,,,,,
110,[557],Prison Break,prison-break,https://www.igdb.com/collections/prison-break,f7e3aa94-3844-1485-3d12-1c5deb8b5b48,1,NaN,NaN
376,"[2028, 10274, 10275, 16121]",Elven Legacy,elven-legacy,https://www.igdb.com/collections/elven-legacy,ff6268cd-0c09-f7df-ea1c-c66b80870158,1,NaN,NaN
229,"[1023, 1024, 10393, 10394, 65862]",Hacker Evolution,hacker-evolution,https://www.igdb.com/collections/hacker-evolution,89fa0307-7f15-14fc-3c8d-527ced1e40ab,1,NaN,NaN
69,"[18928, 56624, 57033, 57034, 77971, 78448, 784...",The Legend of Sword and Fairy,the-legend-of-sword-and-fairy,https://www.igdb.com/collections/the-legend-of...,2a765dfd-417f-091e-5d38-d75fafa0e9b1,1,NaN,NaN
274,"[1233, 1232, 1230, 45253, 1231, 129891, 70514,...",Phantasy Star,phantasy-star,https://www.igdb.com/collections/phantasy-star,93643c54-46af-2d6a-228f-9df6207e52fe,1,NaN,NaN
...,...,...,...,...,...,...,...,...
456,"[2249, 2250, 2251]",Deathspank,deathspank,https://www.igdb.com/collections/deathspank,c92955ed-b1ae-fad7-eb95-440e5e49740d,1,NaN,NaN
184,"[794, 810, 924, 934, 935, 940, 2588, 4323, 882...",Wing Commander,wing-commander,https://www.igdb.com/collections/wing-commander,83baadb3-318b-8860-86ca-c2c4d21df0dd,1,NaN,NaN
224,"[612, 919, 116634]",Beneath a Steel Sky,beneath-a-steel-sky,https://www.igdb.com/collections/beneath-a-ste...,40fc2f01-2af0-f24e-9cc4-3b18f0d2183f,1,NaN,NaN
332,"[1677, 1678, 1679, 1680, 1681, 1682, 1683, 263...",Wild Arms,wild-arms,https://www.igdb.com/collections/wild-arms,8ac08e29-4696-043e-9811-c8561f404372,1,NaN,NaN
149,"[840, 962, 963, 285, 71480, 10743, 350134]",Railroad Tycoon,railroad-tycoon,https://www.igdb.com/collections/railroad-tycoon,13479154-dc89-bac9-72c6-87d981e74d90,1,NaN,NaN

In [22]:
# artworks_db.to_csv('artworks.csv')
# companies_db.to_csv('companies.csv')
# covers_db.to_csv('covers.csv')
# franchises_db.to_csv('franchises.csv')
# games_db.to_csv('games.csv')
# game_modes_db.to_csv('game_modes.csv')
# release_dates_db.to_csv('release_dates.csv')
# keywords_db.to_csv('keywords.csv')
# screenshots_db.to_csv('screenshots.csv')
# themes_db.to_csv('themes.csv')
# genres_db.to_csv('genres.csv')
# involved_companies_db.to_csv('involved_companies.csv')
# platforms_db.to_csv('platforms.csv')
collections_db.to_csv('collections.csv')